#pragma once
#include <stdint.h>
#include <math.h>
#include "ConversionHelper.h"
#include <assert.h>
#define RPM2RadSec (3.14159265358979323846 / 30) // 2-4 merge: required by activated BK Motor3 conversion functions

// Manually modified conversion functions for CAN messages. 
// This file should only contain the CAM messages that we can absolutely not handle using the DBC tools
// These messages need to be marked in the tool as 'no C generation'


// message ID 0x295 Motor3Status1
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			uint64_t currentTorque : 15;    //Nm
			uint64_t torqueDir : 1;
			int64_t currentSpeed : 16;    //RPM
			uint64_t motorTemp : 8;    //degrees C
			uint64_t contTemp : 8;    //degrees C
			uint64_t errorCode : 6;
			uint64_t faultLevel : 2;
		} signals;
	} raw;
	double motorSpeedRpm;
	double motorSpeedRadSec;
	double currentTorque;
	double motorTemp;
	double contTemp;
} Motor3Status1_t;


// This code is only used in testing. This message is generated by the motor
/* 2-4 merge: BK function definition activated from OhmioLibraries_BK. */
static void Motor3Status1_ToCan(Motor3Status1_t * msg)
{
	// set the torque and speed directions according to sign of values
	msg->raw.signals.direction = (msg->motorSpeedRpm >= 0) ? 1 : 2;
	msg->raw.signals.torqueDir = (msg->currentTorque >= 0) ? 0 : 1;

	assert(msg->raw.signals.controlModel <= 3);
	assert(msg->currentTorque >= -3000 && msg->currentTorque <= 3000);
	assert(msg->motorTemp >= -40 && msg->motorTemp <= 150);
	assert(msg->contTemp >= -40 && msg->contTemp <= 150);
	assert(msg->raw.signals.errorCode <= 63);
	assert(msg->raw.signals.faultLevel <= 2);
	msg->raw.signals.currentTorque = RoundLimitSigned(fabs(msg->currentTorque), 1.0, 15);
	msg->raw.signals.currentSpeed = RoundLimitSigned(fabs(msg->motorSpeedRpm), 1.0, 16);
	assert(msg->motorTemp + 40 >= 0);
	msg->raw.signals.motorTemp = RoundLimitUnsigned(msg->motorTemp + 40, 1, 8);
	assert(msg->contTemp + 40 >= 0);
	msg->raw.signals.contTemp = RoundLimitUnsigned(msg->contTemp + 40, 1, 8);
}
// Extract the data from motor message. Get sign from the right bits
// and convert speed to rad/sec
/* 2-4 merge: BK function definition activated from OhmioLibraries_BK. */
static void Motor3Status1_FromCan(Motor3Status1_t * msg)
{
	msg->currentTorque = msg->raw.signals.currentTorque * 1.0;
	if (msg->raw.signals.torqueDir == 1)
	{	// torqueDir is 1 if negative 
		msg->currentTorque = -msg->currentTorque;
	}
	msg->motorSpeedRpm = msg->raw.signals.currentSpeed * 1.0;
	if (msg->raw.signals.direction == 2)
	{	// direction is 2 if negative
		msg->motorSpeedRpm = -msg->motorSpeedRpm;
	}
	msg->motorSpeedRadSec = msg->motorSpeedRpm * RPM2RadSec;
	msg->motorTemp = msg->raw.signals.motorTemp * 1.0 - 40;
	msg->contTemp = msg->raw.signals.contTemp * 1.0 - 40;
}
// message ID 0x161 Motor3ReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			int64_t speed : 16;    // RPM
			uint64_t torque : 16;    //Nm
			uint64_t throttleOpenDegree : 8;    //%
			uint64_t count : 8;
			uint64_t reserved : 2;
			uint64_t damp : 2;
			uint64_t reserved1 : 2;
			uint64_t lame : 2;
		} signals;
	} raw;
	double speedRadSec;
	double throttleOpenDegree;
} Motor3ReqMsg_t;

// convert motor request to CAN. This is called by drive control.
// The caller should set the speedRadSeec (signed) and modes
// this function will handle the direction and conversion to RPM.
/* 2-4 merge: BK function definition activated from OhmioLibraries_BK. */
static void Motor3ReqMsg_ToCan(Motor3ReqMsg_t * msg)
{
	msg->raw.signals.direction = (msg->speedRadSec >= 0) ? 1 : 2;
	msg->raw.signals.speed = RoundLimitSigned(fabs(msg->speedRadSec) / RPM2RadSec, 1.0, 16);

	assert(msg->raw.signals.controlModel <= 3);
	assert(msg->raw.signals.direction <= 2);
	assert(msg->raw.signals.speed >= 0 && msg->raw.signals.speed <= 10000);
	assert(msg->throttleOpenDegree <= 100);
	assert(msg->throttleOpenDegree >= 0);
	assert(msg->raw.signals.count <= 255);
	assert(msg->raw.signals.damp <= 2);
	assert(msg->raw.signals.lame <= 2);
	msg->raw.signals.throttleOpenDegree = RoundLimitUnsigned(msg->throttleOpenDegree, 0.4, 8);
}
// This should generally be done by the motor  but can be called by the 
// UI to display the request. 
// Handles speed sign and conversion from RPM
/* 2-4 merge: BK function definition activated from OhmioLibraries_BK. */
static void Motor3ReqMsg_FromCan(Motor3ReqMsg_t * msg)
{
	msg->speedRadSec = msg->raw.signals.speed * RPM2RadSec;
	if (msg->raw.signals.direction == 2)
	{	// direction is 2 if negative
		msg->speedRadSec = -msg->speedRadSec;
	}
	msg->throttleOpenDegree = msg->raw.signals.throttleOpenDegree * 0.4;
}
// only needs the error flags for steering 
// message ID 0x12 ErrorFrontSteering
// message ID 0x13 ErrorRearSteering
enum SteerErrorCode
{
	Steer_Req_Comms = 0,
	Steer_Req_Seq,
	Steer_Motor_Blocked,
	Steer_Over_Heat,
	Steer_Angle_Sensor,
	Steer_Motor_Pos_Sensor,
	Steer_Volt_Out_Of_Range,
	
	//always add error codes above this
	Steer_NumErrorCodes,
};

// Helpers for split WP in low 16 bits and high 3 bits
uint32_t WayPointFromParts(uint64_t low, uint64_t high);

uint64_t WayPointToLow(uint32_t wp);

uint64_t WayPointToHigh(uint32_t wp);
// end Helpers for split WP 


// this message has special treatment for WP that is split into 2 sections
// message ID 0x300 DynamicTrackValidationMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			int64_t x : 20;    //m
			int64_t y : 20;    //m
			uint64_t waypointHigh : 3;
		} signals;
	} raw;
	double x;
	double y;
	uint32_t waypoint;
} DynamicTrackValidationMsg_t;
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void DynamicTrackValidationMsg_ToCan(DynamicTrackValidationMsg_t * msg) 
{ 
    msg->raw.signals.x = RoundLimitSigned(msg->x, 0.01, 20);
    msg->raw.signals.y = RoundLimitSigned(msg->y, 0.01, 20);
}
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void DynamicTrackValidationMsg_FromCan(DynamicTrackValidationMsg_t * msg) 
{ 
    msg->x = msg->raw.signals.x * 0.01;
    msg->y = msg->raw.signals.y * 0.01;
}
// this message has special treatment for WP that is split into 2 sections
// message ID 0x326 StopReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			uint64_t decelerate : 8;    //10mm/s2
			uint64_t deceFlag : 1;
			uint64_t waypointHigh : 3;
			uint64_t reason : 4;
		} signals;
	} raw;
	double decelerate;
	uint32_t waypoint;
} StopReqMsg_t;
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void StopReqMsg_ToCan(StopReqMsg_t * msg) 
{ 
    assert(msg->raw.signals.deceFlag <= 1);
    assert(msg->decelerate >= 0);
    msg->raw.signals.decelerate = RoundLimitUnsigned(msg->decelerate, 10, 8);
}
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void StopReqMsg_FromCan(StopReqMsg_t * msg) 
{ 
    msg->decelerate = msg->raw.signals.decelerate * 10 * 1.0;
}
// this message has special treatment for WP that is split into 2 sections
// message ID 0x2C5 DeviationReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			int64_t offset : 8;    //m
			uint64_t speed : 8;    //m/s
			uint64_t InFlag : 1;
			uint64_t acceleration : 3;    //m/s^2
			uint64_t OffsetActive : 1;
			uint64_t NoDeviation : 1;
			uint64_t waypointHigh : 3;
		} signals;
	} raw;
	double offset;
	double speed;
	double acceleration;
	uint32_t waypoint;
} DeviationReqMsg_t;
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void DeviationReqMsg_ToCan(DeviationReqMsg_t * msg) 
{ 
    assert(msg->offset >= -4 && msg->offset <= 4);
    assert(msg->speed <= 10);
    assert(msg->raw.signals.InFlag <= 1);
    assert(msg->acceleration <= 0.7);
    assert(msg->raw.signals.OffsetActive <= 1);
    assert(msg->raw.signals.NoDeviation <= 1);
    msg->raw.signals.offset = RoundLimitSigned(msg->offset, 0.032, 8);
    assert(msg->speed >= 0);
    msg->raw.signals.speed = RoundLimitUnsigned(msg->speed, 0.04, 8);
    assert(msg->acceleration >= 0);
    msg->raw.signals.acceleration = RoundLimitUnsigned(msg->acceleration, 0.1, 3);
}
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void DeviationReqMsg_FromCan(DeviationReqMsg_t * msg) 
{ 
    msg->offset = msg->raw.signals.offset * 0.032;
    msg->speed = msg->raw.signals.speed * 0.04;
    msg->acceleration = msg->raw.signals.acceleration * 0.1;
}
// message ID 0x21A FusionFrontLongitude
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			int64_t longitude : 36;    //degrees
			uint64_t forwardConf : 14;    //m
			uint64_t heading : 12;    //degree
			uint64_t sync : 2;
		} signals;
	} raw;
	double longitude;
	double forwardConf;
	double heading;
} FusionFrontLongitude_t;
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void FusionFrontLongitude_ToCan(FusionFrontLongitude_t * msg) 
{ 
    assert(msg->longitude >= -180 && msg->longitude <= 180);
    assert(msg->forwardConf <= 16.383);
    assert(msg->heading <= 359.9);
    assert(msg->raw.signals.sync <= 3);
    msg->raw.signals.longitude = RoundLimitSigned(msg->longitude, 0.00000001, 36);
    assert(msg->forwardConf >= 0);
    msg->raw.signals.forwardConf = RoundLimitUnsigned(msg->forwardConf, 0.001, 14);
    assert(msg->heading >= 0);
    msg->raw.signals.heading = RoundLimitUnsigned(msg->heading, 0.1, 12);
}
/* 2-4 merge: BK function definition activated at Origin additionalDbcCan.h location by user direction. */
static void FusionFrontLongitude_FromCan(FusionFrontLongitude_t * msg) 
{ 
    msg->longitude = msg->raw.signals.longitude * 0.00000001;
    msg->forwardConf = msg->raw.signals.forwardConf * 0.001;
    msg->heading = msg->raw.signals.heading * 0.1;
}