#pragma once

// Manually modified conversion functions for CAN messages. 
// This file should only contain the CAM messages that we can absolutely not handle using the DBC tools
// These messages need to be marked in the tool as 'no C generation'


// message ID 0x295 Motor3Status1
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			uint64_t currentTorque : 15;    //Nm
			uint64_t torqueDir : 1;
			int64_t currentSpeed : 16;    //RPM
			uint64_t motorTemp : 8;    //degrees C
			uint64_t contTemp : 8;    //degrees C
			uint64_t errorCode : 6;
			uint64_t faultLevel : 2;
		} signals;
	} raw;
	double motorSpeedRpm;
	double motorSpeedRadSec;
	double currentTorque;
	double motorTemp;
	double contTemp;
} Motor3Status1_t;

#define RPM2RadSec (3.14159265358979323846 / 30) // rad per sec = RMP * 2pi / 60

// This code is only used in testing. This message is generated by the motor
static void Motor3Status1_ToCan(Motor3Status1_t * msg)
{
	// set the torque and speed directions according to sign of values
	msg->raw.signals.direction = (msg->motorSpeedRpm >= 0) ? 1 : 2;
	msg->raw.signals.torqueDir = (msg->currentTorque >= 0) ? 0 : 1;

	assert(msg->raw.signals.controlModel <= 3);
	assert(msg->currentTorque >= -3000 && msg->currentTorque <= 3000);
	assert(msg->motorTemp >= -40 && msg->motorTemp <= 150);
	assert(msg->contTemp >= -40 && msg->contTemp <= 150);
	assert(msg->raw.signals.errorCode <= 63);
	assert(msg->raw.signals.faultLevel <= 2);
	msg->raw.signals.currentTorque = RoundLimitSigned(fabs(msg->currentTorque), 1.0, 15);
	msg->raw.signals.currentSpeed = RoundLimitSigned(fabs(msg->motorSpeedRpm), 1.0, 16);
	assert(msg->motorTemp + 40 >= 0);
	msg->raw.signals.motorTemp = RoundLimitUnsigned(msg->motorTemp + 40, 1, 8);
	assert(msg->contTemp + 40 >= 0);
	msg->raw.signals.contTemp = RoundLimitUnsigned(msg->contTemp + 40, 1, 8);
}


// Extract the data from motor message. Get sign from the right bits
// and convert speed to rad/sec
static void Motor3Status1_FromCan(Motor3Status1_t * msg)
{
	msg->currentTorque = msg->raw.signals.currentTorque * 1.0;
	if (msg->raw.signals.torqueDir == 1)
	{	// torqueDir is 1 if negative 
		msg->currentTorque = -msg->currentTorque;
	}
	msg->motorSpeedRpm = msg->raw.signals.currentSpeed * 1.0;
	if (msg->raw.signals.direction == 2)
	{	// direction is 2 if negative
		msg->motorSpeedRpm = -msg->motorSpeedRpm;
	}
	msg->motorSpeedRadSec = msg->motorSpeedRpm * RPM2RadSec;
	msg->motorTemp = msg->raw.signals.motorTemp * 1.0 - 40;
	msg->contTemp = msg->raw.signals.contTemp * 1.0 - 40;
}



// message ID 0x161 Motor3ReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			int64_t speed : 16;    // RPM
			uint64_t torque : 16;    //Nm
			uint64_t throttleOpenDegree : 8;    //%
			uint64_t count : 8;
			uint64_t reserved : 2;
			uint64_t damp : 2;
			uint64_t reserved1 : 2;
			uint64_t lame : 2;
		} signals;
	} raw;
	double speedRadSec;
	double throttleOpenDegree;
} Motor3ReqMsg_t;

// convert motor request to CAN. This is called by drive control.
// The caller should set the speedRadSeec (signed) and modes
// this function will handle the direction and conversion to RPM.
static void Motor3ReqMsg_ToCan(Motor3ReqMsg_t * msg)
{
	msg->raw.signals.direction = (msg->speedRadSec >= 0) ? 1 : 2;
	msg->raw.signals.speed = RoundLimitSigned(fabs(msg->speedRadSec) / RPM2RadSec, 1.0, 16);

	assert(msg->raw.signals.controlModel <= 3);
	assert(msg->raw.signals.direction <= 2);
	assert(msg->raw.signals.speed >= 0 && msg->raw.signals.speed <= 10000);
	assert(msg->throttleOpenDegree <= 100);
	assert(msg->throttleOpenDegree >= 0);
	assert(msg->raw.signals.count <= 255);
	assert(msg->raw.signals.damp <= 2);
	assert(msg->raw.signals.lame <= 2);
	msg->raw.signals.throttleOpenDegree = RoundLimitUnsigned(msg->throttleOpenDegree, 0.4, 8);
}

// This should generally be done by the motor  but can be called by the 
// UI to display the request. 
// Handles speed sign and conversion from RPM
static void Motor3ReqMsg_FromCan(Motor3ReqMsg_t * msg)
{
	msg->speedRadSec = msg->raw.signals.speed * RPM2RadSec;
	if (msg->raw.signals.direction == 2)
	{	// direction is 2 if negative
		msg->speedRadSec = -msg->speedRadSec;
	}
	msg->throttleOpenDegree = msg->raw.signals.throttleOpenDegree * 0.4;
}

// only needs the error flags for steering 
// message ID 0x12 ErrorFrontSteering
// message ID 0x13 ErrorRearSteering
enum SteerErrorCode
{
	Steer_Req_Comms = 0,
	Steer_Req_Seq,
	Steer_Motor_Blocked,
	Steer_Over_Heat,
	Steer_Angle_Sensor,
	Steer_Motor_Pos_Sensor,
	Steer_Volt_Out_Of_Range,
	
	//always add error codes above this
	Steer_NumErrorCodes,
};
