#pragma once
#include <stdint.h>
#include <math.h>
#include "ConversionHelper.h"

// Manually modified conversion functions for CAN messages. 
// This file should only contain the CAM messages that we can absolutely not handle using the DBC tools
// These messages need to be marked in the tool as 'no C generation'


// message ID 0x295 Motor3Status1
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			uint64_t currentTorque : 15;    //Nm
			uint64_t torqueDir : 1;
			int64_t currentSpeed : 16;    //RPM
			uint64_t motorTemp : 8;    //degrees C
			uint64_t contTemp : 8;    //degrees C
			uint64_t errorCode : 6;
			uint64_t faultLevel : 2;
		} signals;
	} raw;
	double motorSpeedRpm;
	double motorSpeedRadSec;
	double currentTorque;
	double motorTemp;
	double contTemp;
} Motor3Status1_t;


// This code is only used in testing. This message is generated by the motor
void Motor3Status1_ToCan(Motor3Status1_t * msg);


// Extract the data from motor message. Get sign from the right bits
// and convert speed to rad/sec
void Motor3Status1_FromCan(Motor3Status1_t * msg);



// message ID 0x161 Motor3ReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t controlModel : 2;
			uint64_t direction : 2;
			uint64_t mode : 4;
			int64_t speed : 16;    // RPM
			uint64_t torque : 16;    //Nm
			uint64_t throttleOpenDegree : 8;    //%
			uint64_t count : 8;
			uint64_t reserved : 2;
			uint64_t damp : 2;
			uint64_t reserved1 : 2;
			uint64_t lame : 2;
		} signals;
	} raw;
	double speedRadSec;
	double throttleOpenDegree;
} Motor3ReqMsg_t;

// convert motor request to CAN. This is called by drive control.
// The caller should set the speedRadSeec (signed) and modes
// this function will handle the direction and conversion to RPM.
void Motor3ReqMsg_ToCan(Motor3ReqMsg_t * msg);

// This should generally be done by the motor  but can be called by the 
// UI to display the request. 
// Handles speed sign and conversion from RPM
void Motor3ReqMsg_FromCan(Motor3ReqMsg_t * msg);

// only needs the error flags for steering 
// message ID 0x12 ErrorFrontSteering
// message ID 0x13 ErrorRearSteering
enum SteerErrorCode
{
	Steer_Req_Comms = 0,
	Steer_Req_Seq,
	Steer_Motor_Blocked,
	Steer_Over_Heat,
	Steer_Angle_Sensor,
	Steer_Motor_Pos_Sensor,
	Steer_Volt_Out_Of_Range,
	
	//always add error codes above this
	Steer_NumErrorCodes,
};

// Helpers for split WP in low 16 bits and high 3 bits
uint32_t WayPointFromParts(uint64_t low, uint64_t high);

uint64_t WayPointToLow(uint32_t wp);

uint64_t WayPointToHigh(uint32_t wp);
// end Helpers for split WP 


// this message has special treatment for WP that is split into 2 sections
// message ID 0x300 DynamicTrackValidationMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			int64_t x : 20;    //m
			int64_t y : 20;    //m
			uint64_t waypointHigh : 3;
		} signals;
	} raw;
	double x;
	double y;
	uint32_t waypoint;
} DynamicTrackValidationMsg_t;


void DynamicTrackValidationMsg_ToCan(DynamicTrackValidationMsg_t * msg);

void DynamicTrackValidationMsg_FromCan(DynamicTrackValidationMsg_t * msg);


// this message has special treatment for WP that is split into 2 sections
// message ID 0x326 StopReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			uint64_t decelerate : 8;    //10mm/s2
			uint64_t deceFlag : 1;
			uint64_t waypointHigh : 3;
			uint64_t reason : 4;
		} signals;
	} raw;
	double decelerate;
	uint32_t waypoint;
} StopReqMsg_t;


void StopReqMsg_ToCan(StopReqMsg_t * msg);

void StopReqMsg_FromCan(StopReqMsg_t * msg);


// this message has special treatment for WP that is split into 2 sections
// message ID 0x2C5 DeviationReqMsg
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			uint64_t waypointLow : 16;
			int64_t offset : 8;    //m
			uint64_t speed : 8;    //m/s
			uint64_t InFlag : 1;
			uint64_t acceleration : 3;    //m/s^2
			uint64_t OffsetActive : 1;
			uint64_t NoDeviation : 1;
			uint64_t waypointHigh : 3;
		} signals;
	} raw;
	double offset;
	double speed;
	double acceleration;
	uint32_t waypoint;
} DeviationReqMsg_t;


void DeviationReqMsg_ToCan(DeviationReqMsg_t * msg);

void DeviationReqMsg_FromCan(DeviationReqMsg_t * msg);

// message ID 0x21A FusionFrontLongitude
typedef struct {
	union
	{
		uint8_t buf[8];
		struct
		{
			int64_t longitude : 36;    //degrees
			uint64_t forwardConf : 14;    //m
			uint64_t heading : 12;    //degree
			uint64_t sync : 2;
		} signals;
	} raw;
	double longitude;
	double forwardConf;
	double heading;
} FusionFrontLongitude_t;


void FusionFrontLongitude_ToCan(FusionFrontLongitude_t * msg);

void FusionFrontLongitude_FromCan(FusionFrontLongitude_t * msg);
